import { spawn } from 'node:child_process';
const CH = '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome';
const sleep = ms => new Promise(r=>setTimeout(r,ms));
const port = 7990 + Math.floor(Math.random()*9);
const chrome = spawn(CH, ['--headless=new','--disable-gpu','--no-sandbox',`--remote-debugging-port=${port}`,'--user-data-dir=/tmp/cdp-top-'+port,'about:blank']);
chrome.stderr.on('data',()=>{});
let ws=null;
for (let i=0;i<60&&!ws;i++){ await sleep(400); try { const l=await (await fetch(`http://127.0.0.1:${port}/json/list`)).json(); ws=l.find(t=>t.type==='page')?.webSocketDebuggerUrl||null; } catch {} }
const sock=new WebSocket(ws); await new Promise(r=>sock.onopen=r);
let id=0; const pend=new Map(); const errs=[];
sock.onmessage=e=>{const m=JSON.parse(e.data); if(m.id&&pend.has(m.id)){pend.get(m.id)(m);pend.delete(m.id);return;} if(m.method==='Runtime.exceptionThrown') errs.push(String(m.params.exceptionDetails?.exception?.description||'').slice(0,60));};
const send=(m,p={})=>new Promise(res=>{const i=++id;pend.set(i,res);sock.send(JSON.stringify({id:i,method:m,params:p}))});
const ev=async e=>{const r=await send('Runtime.evaluate',{expression:e,returnByValue:true,awaitPromise:true}); if(r.result?.exceptionDetails) return '（异常）'; return r.result?.result?.value;};
const ck=(l,g,w)=>{const ok=JSON.stringify(g)===JSON.stringify(w);console.log(`    ${ok?'✅':'❌'} ${l}：${JSON.stringify(g)}`);return ok;};
await send('Page.enable'); await send('Runtime.enable'); await send('Network.enable'); await send('Network.setCacheDisabled',{cacheDisabled:true});
await send('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:3,mobile:true});
let pass=true;
console.log('  【「我的」页】');
await send('Page.navigate',{url:'https://goodprices.online/market/?mine=1&v='+Math.random().toString(36).slice(2)}); await sleep(4300);
pass = ck('顶部按钮文字', await ev(`document.querySelector('#postToggle').textContent.trim()`), '我要出一件') && pass;
pass = ck('它在最顶部（在瀑布流上方）', await ev(`document.querySelector('#postToggle').getBoundingClientRect().bottom <= document.querySelector('.wall').getBoundingClientRect().top + 1`), true) && pass;
pass = ck('样式与「发布」一致（都是 btn、同宽）', await ev(`(() => { const a=document.querySelector('#postToggle'), b=document.querySelector('#submit'); return a.className === b.className && Math.abs(a.getBoundingClientRect().width - b.getBoundingClientRect().width) < 2; })()`), true) && pass;
pass = ck('「我发的」这几个字没了', await ev(`!document.getElementById('listTitle') && !document.body.textContent.includes('我发的')`), true) && pass;
pass = ck('原来的悬浮按钮没了', await ev(`!document.querySelector('.fab')`), true) && pass;
console.log('  【点它能不能开表单】');
pass = ck('打开表单', await ev(`(async () => { document.querySelector('#postToggle').click(); await new Promise(r=>setTimeout(r,700)); return document.querySelector('#postCard').classList.contains('is-open') && !!document.querySelector('#postCard form'); })()`), true) && pass;
pass = ck('表单打开时顶部按钮收起', await ev(`getComputedStyle(document.querySelector('#postToggle')).display`), 'none') && pass;
await ev(`document.querySelector('#postClose').click()`); await sleep(500);
console.log('  【市场页】');
await send('Page.navigate',{url:'https://goodprices.online/market/?v='+Math.random().toString(36).slice(2)}); await sleep(4200);
pass = ck('市场页看不到这个入口', await ev(`getComputedStyle(document.querySelector('#postToggle')).display`), 'none') && pass;
const { data } = (await send('Page.captureScreenshot',{format:'png'})).result;
if (data) require('node:fs').writeFileSync('/tmp/mine-top.png', Buffer.from(data,'base64'));
console.log('  报错: ' + (errs.length ? errs.join(' | ') : '（无）'));
sock.close(); chrome.kill();
console.log(pass ? '  全部通过 ✅' : '  有失败项 ❌');
process.exit(pass ? 0 : 1);
